/**
 * Generated by scripts/fetch-records.ts. Do not edit by hand.
 */

import type { SerialisedRecord } from '@/lib/tide/record'

export const RECORD_LOADERS: Record<string, () => Promise<SerialisedRecord>> = {
  'ioc-benoa': () =>
    import('./ioc-benoa.json').then((m) => m.default as unknown as SerialisedRecord),
}
