import type { Metadata, Viewport } from 'next'
import { Newsreader, Inter_Tight, Roboto_Mono } from 'next/font/google'
import { SITE_URL } from '@/lib/view/site'
import './globals.css'

/** Self-hosted via next/font (PRD §12) — no runtime request to a font CDN. */
const prose = Newsreader({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-prose',
})

const ui = Inter_Tight({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ui',
})

const mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono',
})

/**
 * Asset URLs carry the basePath themselves. A static export lives under the
 * repository name on Pages, and an icon path missing that prefix resolves to
 * the domain root and quietly 404s.
 */
const base = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

/**
 * Where the site is published. Social cards need absolute URLs, and without a
 * metadataBase Next resolves them against localhost — a share preview that
 * works in development and shows nothing anywhere else.
 *
 * SITE_URL lives in lib/view/site now, shared with the sitemap and with every
 * page's canonical, and it is stored without a trailing slash so those can
 * join paths to it cleanly. metadataBase needs the slash back: without it a
 * relative asset like og.png resolves to the domain root rather than into the
 * repository subdirectory, and the card silently 404s.
 */
const METADATA_BASE = new URL(`${SITE_URL}/`)

const DESCRIPTION =
  'Mencocokkan komponen pasang surut dari pengamatan tinggi muka laut dengan kuadrat terkecil, melaporkan kondisi penyelesaiannya, dan menolak apa yang tidak didukung rekaman. Alat edukasi, bukan untuk navigasi.'

export const metadata: Metadata = {
  metadataBase: METADATA_BASE,
  title: {
    default: 'Tide Analysis — analisis harmonik pasang surut',
    template: '%s · Tide Analysis',
  },
  description: DESCRIPTION,
  applicationName: 'Tide Analysis',
  icons: {
    icon: [
      /* The vector first: it stays crisp on any tab, at any zoom. */
      { url: `${base}/favicon.svg`, type: 'image/svg+xml' },
      { url: `${base}/icons/icon-32.png`, sizes: '32x32', type: 'image/png' },
      { url: `${base}/icons/icon-16.png`, sizes: '16x16', type: 'image/png' },
    ],
    apple: [{ url: `${base}/apple-touch-icon.png`, sizes: '180x180', type: 'image/png' }],
    /*
     * The manifest is a static file with relative icon paths, linked from
     * here rather than generated by app/manifest.ts. Both of Next's routes to
     * a manifest — the metadata field and the generated file — emit an href
     * stripped of the basePath, which 404s under a repository subdirectory.
     * Relative paths inside the file resolve against the file's own location,
     * so the same manifest is correct in development and in production.
     */
    other: [{ rel: 'manifest', url: `${base}/site.webmanifest` }],
  },
  appleWebApp: {
    capable: true,
    title: 'Tide Analysis',
    statusBarStyle: 'black-translucent',
  },
  openGraph: {
    type: 'website',
    siteName: 'Tide Analysis',
    title: 'Tide Analysis — analisis harmonik pasang surut',
    description: DESCRIPTION,
    images: [
      {
        url: 'og.png',
        width: 1200,
        height: 630,
        alt: 'Tide Analysis — fit the tide, then predict it forward',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tide Analysis — analisis harmonik pasang surut',
    description: DESCRIPTION,
    images: ['og.png'],
  },
}

export const viewport: Viewport = {
  /*
   * The paper the site is printed on, so the browser chrome matches it.
   * The one place a raw value is unavoidable — this is emitted as a meta tag
   * before any stylesheet loads, so it cannot read --colour-paper. Keep it in
   * step with that token by hand.
   */
  themeColor: '#F7F3E9',
  colorScheme: 'light',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id" className={`${prose.variable} ${ui.variable} ${mono.variable}`}>
      <body className="min-h-screen bg-paper text-ink antialiased">{children}</body>
    </html>
  )
}
